import { useState, useEffect } from 'react'
import { useRouter } from 'next/router';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  const router = useRouter();
  const [tweet, setTweet] = useState('asdf');
  const [token, setToken] = useState({});
  useEffect(() => {
    // const query = new URLSearchParams(this.props.location.search);
    const { token, expires_at } = router.query;
    localStorage.setItem('token', JSON.stringify({
      token_type: 'bearer',
      scope: 'tweet.write users.read tweet.read',
      // fix expires_at
      expires_at: expires_at,
      access_token: token,
    }))
    console.log(token, expires_at);
  });

  const sendTweet = async () => {
    const data = await fetch('https://api.twitter.com/2/tweets?ids=22', {
      cors: 'no-cors',
      headers: {
        'Access-Control-Allow-Origin': 'api.twitter.com'
      }
    });
    console.log(await data.json())
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Disappearing Tweets</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Disappearing Tweet!</a>
        </h1>

        <p className={styles.description}>
          Get started by writing your tweet.
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <textarea type={'text'} value={tweet} onChange={(e) => {setTweet(e.target.value)}}></textarea>
          </div>

          <div className={styles.card}>
            <button onClick={sendTweet} >send tweet</button>
          </div>

          <div className={styles.card}>
            <select>
              <option>15 minutes</option>
              <option>30 minutes</option>
              <option>45 minutes</option>
              <option>1 hour</option>
              <option>6 hours</option>
              <option>12 hours</option>
              <option>24 hours</option>
              <option>48 hours</option>
              <option>72 hours</option>
            </select>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
